fragment TechParts on Tech {
  __typename
  slug
  title
  year
  date
  description
  coverImage
  tags
  categories
  type
  body
}

fragment LifeParts on Life {
  __typename
  slug
  title
  year
  date
  description
  coverImage
  categories
  type
  body
}
