//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  tech: Tech;
  techConnection: TechConnection;
  life: Life;
  lifeConnection: LifeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTechArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTechConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TechFilter>;
};


export type QueryLifeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLifeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LifeFilter>;
};

export type DocumentFilter = {
  tech?: InputMaybe<TechFilter>;
  life?: InputMaybe<LifeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Tech | Life | Folder;

export type Tech = Node & Document & {
  __typename?: 'Tech';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  year: Scalars['Float']['output'];
  date: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  categories?: Maybe<Scalars['String']['output']>;
  type: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TechFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  date?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  categories?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TechConnectionEdges = {
  __typename?: 'TechConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tech>;
};

export type TechConnection = Connection & {
  __typename?: 'TechConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TechConnectionEdges>>>;
};

export type Life = Node & Document & {
  __typename?: 'Life';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  year: Scalars['Float']['output'];
  date: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  categories?: Maybe<Scalars['String']['output']>;
  type: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LifeFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  date?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  categories?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type LifeConnectionEdges = {
  __typename?: 'LifeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Life>;
};

export type LifeConnection = Connection & {
  __typename?: 'LifeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LifeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateTech: Tech;
  createTech: Tech;
  updateLife: Life;
  createLife: Life;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateTechArgs = {
  relativePath: Scalars['String']['input'];
  params: TechMutation;
};


export type MutationCreateTechArgs = {
  relativePath: Scalars['String']['input'];
  params: TechMutation;
};


export type MutationUpdateLifeArgs = {
  relativePath: Scalars['String']['input'];
  params: LifeMutation;
};


export type MutationCreateLifeArgs = {
  relativePath: Scalars['String']['input'];
  params: LifeMutation;
};

export type DocumentUpdateMutation = {
  tech?: InputMaybe<TechMutation>;
  life?: InputMaybe<LifeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  tech?: InputMaybe<TechMutation>;
  life?: InputMaybe<LifeMutation>;
};

export type TechMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  categories?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type LifeMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  categories?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TechPartsFragment = { __typename: 'Tech', slug: string, title: string, year: number, date: string, description?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, categories?: string | null, type: string, body?: any | null };

export type LifePartsFragment = { __typename: 'Life', slug: string, title: string, year: number, date: string, description?: string | null, coverImage?: string | null, categories?: string | null, type: string, body?: any | null };

export type TechQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TechQuery = { __typename?: 'Query', tech: { __typename: 'Tech', id: string, slug: string, title: string, year: number, date: string, description?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, categories?: string | null, type: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TechConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TechFilter>;
}>;


export type TechConnectionQuery = { __typename?: 'Query', techConnection: { __typename?: 'TechConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TechConnectionEdges', cursor: string, node?: { __typename: 'Tech', id: string, slug: string, title: string, year: number, date: string, description?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, categories?: string | null, type: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type LifeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LifeQuery = { __typename?: 'Query', life: { __typename: 'Life', id: string, slug: string, title: string, year: number, date: string, description?: string | null, coverImage?: string | null, categories?: string | null, type: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LifeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LifeFilter>;
}>;


export type LifeConnectionQuery = { __typename?: 'Query', lifeConnection: { __typename?: 'LifeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LifeConnectionEdges', cursor: string, node?: { __typename: 'Life', id: string, slug: string, title: string, year: number, date: string, description?: string | null, coverImage?: string | null, categories?: string | null, type: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const TechPartsFragmentDoc = gql`
    fragment TechParts on Tech {
  __typename
  slug
  title
  year
  date
  description
  coverImage
  tags
  categories
  type
  body
}
    `;
export const LifePartsFragmentDoc = gql`
    fragment LifeParts on Life {
  __typename
  slug
  title
  year
  date
  description
  coverImage
  categories
  type
  body
}
    `;
export const TechDocument = gql`
    query tech($relativePath: String!) {
  tech(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TechParts
  }
}
    ${TechPartsFragmentDoc}`;
export const TechConnectionDocument = gql`
    query techConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TechFilter) {
  techConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TechParts
      }
    }
  }
}
    ${TechPartsFragmentDoc}`;
export const LifeDocument = gql`
    query life($relativePath: String!) {
  life(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LifeParts
  }
}
    ${LifePartsFragmentDoc}`;
export const LifeConnectionDocument = gql`
    query lifeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LifeFilter) {
  lifeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LifeParts
      }
    }
  }
}
    ${LifePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      tech(variables: TechQueryVariables, options?: C): Promise<{data: TechQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechQueryVariables, query: string}> {
        return requester<{data: TechQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechQueryVariables, query: string}, TechQueryVariables>(TechDocument, variables, options);
      },
    techConnection(variables?: TechConnectionQueryVariables, options?: C): Promise<{data: TechConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechConnectionQueryVariables, query: string}> {
        return requester<{data: TechConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TechConnectionQueryVariables, query: string}, TechConnectionQueryVariables>(TechConnectionDocument, variables, options);
      },
    life(variables: LifeQueryVariables, options?: C): Promise<{data: LifeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LifeQueryVariables, query: string}> {
        return requester<{data: LifeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LifeQueryVariables, query: string}, LifeQueryVariables>(LifeDocument, variables, options);
      },
    lifeConnection(variables?: LifeConnectionQueryVariables, options?: C): Promise<{data: LifeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LifeConnectionQueryVariables, query: string}> {
        return requester<{data: LifeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LifeConnectionQueryVariables, query: string}, LifeConnectionQueryVariables>(LifeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.1/content/4ed633c3-6c22-4d50-a0ac-01144dd358ce/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  